### ISSUE TITLE
Add rights on removeconf

### ISSUE THREAD

**Issue by iouston** [ksar-ksar/Dolibarr_removeconf#3]
Salut,
J'avais besoin de ce module pour un de mes dolibarr et pour pemettre à certains utilisateurs de ne pas passer par la fenêtre de confirmation.
Comme ton module proposait par défaut pour tous les utilisateurs, j'ai ajouté un droit spécifique pour chaque suppression de confirmation, comme cela je peux trier par utilisateur et ou par groupe qui peut se passer des notifications.
Si ça t'intéresse, voilà ce que j'ai fait
Merci pour ce chouette module !
[removeconf.zip](https://github.com/ksar-ksar/Dolibarr_removeconf/files/4557542/removeconf.zip)

**Comment by ksar-ksar** [comment]
Salut,

Merci pour le code, ça m'a l'air super interressant.
Je peux l'integrer dans le module ?

**Comment by iouston** [comment]
Bien sûr, si ça peut servir à d'autres, c'est avec plaisir

**Comment by ksar-ksar** [comment]
Update V2 avec tes modifications
