### ISSUE TITLE
enhancement on removeconf

### ISSUE THREAD

**Issue by iouston** [ksar-ksar/Dolibarr_removeconf#8]
Hi,
One of our customer paid us to add an enhancement on removeconf.
They add a removeconf on propal validate and a removeconf on project plugin.
For this last feature we send a pull request on dolibarr core to add hook for that in project plugin.
The pr is here → https://github.com/Dolibarr/dolibarr/pull/22809
The new version for remove conf is in attachment.
Have a nice day !
[module_removeconf-2.2.0(1).zip](https://github.com/ksar-ksar/Dolibarr_removeconf/files/10071410/module_removeconf-2.2.0.1.zip)

**Comment by ksar-ksar** [comment]
Thanks!

Your PR has been merged in develop after the creation of v17 no ?
So it will be available on v18 ?

**Comment by iouston** [comment]
Maybe directly available for the 17 no ?
